apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlkey-pv-volume
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/root/volumes/keycloak"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage
          operator: In
          values:
          - mysqlKey
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlkey-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi