apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres  
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: postgres-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"    
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim    
