apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pc-volume-claim
  labels: 
    app: postgres
spec:
  storageClassName: manual
  accesModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi      